# EXERCICIS MÒDUL 3

## Primera Part

Descripció:
En aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris. 

Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”. 

Per a obtenir informació del dataset pots consultar el següent enllaç:

sklearn.datasets.load_iris

Objectius 
Creació d'arrays amb la llibreria numpy. 
Creació de matrius amb la llibreria numpy. 
Ús dels mètodes de la llibreria numpy. 
Utilització de funcions. 


In [52]:
import numpy as np

- Exercici 1 Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [6]:
from sklearn.datasets import load_iris
dades = load_iris()

In [22]:
#Així ho havia fet el primer cop (no és massa operatiu)
print('Els primers 10 registres de data són:')
for x in range(10):
      print(dades.data[x])

Els primers 10 registres de data són:
[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]


In [40]:
data[:10] #Dubte: Per què no cal posar dades.data? 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [23]:
#Així ho havia fet el primer cop (no és massa operatiu)
print('Els primers 10 registres de target són:')
for x in range(10):
    print(dades.target[x])

Els primers 10 registres de target són:
0
0
0
0
0
0
0
0
0
0


In [38]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

- Exercici 2
Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.


In [41]:
data.shape

(150, 4)

In [42]:
target.shape

(150,)

In [44]:
concat=np.concatenate((data, target.reshape(-1,1)), axis =1)

In [45]:
concat

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

- Exercici 3
Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.


In [309]:
mitjana_sepal=round(float(np.mean(data[:,0])),2)
desviacio_sepal=round(float(np.std(data[:,0])),2)
print("La mitjana de la longitud del sèpal és:",mitjana_sepal)
print("La desviació de la longitud del sèpal és:",desviacio_sepal)

La mitjana de la longitud del sèpal és: 5.84
La desviació de la longitud del sèpal és: 0.83


In [364]:
mitjana_petal=round(np.mean(data[:,2]),2)
desviacio_petal=round(np.std(data[:,2]),2)
print("La mitjana de la longitud del pètal és:",mitjana_petal)
print("La desviació de la longitud del pètal és:",desviacio_petal)

La mitjana de la longitud del pètal és: 3.76
La desviació de la longitud del pètal és: 1.76


- Exercici 4
Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior. La utilitzaràs d'aquí endavant.

In [340]:
from numpy import random

number_of_rows = concat.shape[0] #Obtinc número de files
#Obtinc índex aleatoris. Cal posar el Replace?
random_indices = np.random.choice(number_of_rows, size=20, replace=False)
random_rows = concat[random_indices, :]
#Font:https://www.adamsmith.haus/python/answers/how-to-select-random-rows-from-a-numpy-array-in-python

In [341]:
print(random_rows)

[[6.1 2.6 5.6 1.4 2. ]
 [6.5 3.2 5.1 2.  2. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [7.1 3.  5.9 2.1 2. ]
 [5.7 2.6 3.5 1.  1. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.8 2.7 5.1 1.9 2. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [7.7 3.  6.1 2.3 2. ]
 [6.7 3.  5.  1.7 1. ]
 [7.9 3.8 6.4 2.  2. ]
 [6.3 3.4 5.6 2.4 2. ]
 [5.1 3.8 1.5 0.3 0. ]
 [6.  2.2 5.  1.5 2. ]
 [6.4 2.8 5.6 2.1 2. ]
 [4.8 3.4 1.6 0.2 0. ]]


- Exercici 5
Crea una matriu que mostri:  
La mitjana de cada característica per espècie. (mean)
La desviació estàndard de cada característica per espècie. (std)

In [342]:
dades.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [343]:
index_setosa = np.array(np.where((random_rows[:,4]) == 0))
index_versicolor = np.array(np.where((random_rows[:,4]) == 1))
index_virginica = np.array(np.where((random_rows[:,4]) == 2))

In [344]:
#Creo una matriu per cada espècie en les que desaré les seves característiques, i una buida final on desaré 
#els càlculs de mitjana i desviació. A la columna dels 20 registres eliminaré l'última que m'indica l'espècie
#La matriu final tindrà 3 files (una per espècie), i 8 columnes. Les 4 primeres seran els mitjanes de cada 
#característica, i les 4 últimes les seves desviacions.
m1 = np.empty((index_setosa.size,4))
m2 = np.empty((index_versicolor.size,4))
m3 = np.empty((index_virginica.size,4))
matriunoespecies= np.delete(random_rows, 4, axis=1)
matriufinal=np.empty((3,8))

In [345]:
#Empleno les matrius
for x in range(index_setosa.size):
    m1[x,:]=matriunoespecies[index_setosa[0,x],:]
for x in range(index_versicolor.size):
    m2[x,:]=matriunoespecies[index_versicolor[0,x],:]
for x in range(index_virginica.size):
    m3[x,:]=matriunoespecies[index_virginica[0,x],:]
for x in range(4):
    matriufinal[0,x]=m1[:,x].mean()
    matriufinal[0,x+4]=m1[:,x].std()
    matriufinal[1,x]=m2[:,x].mean()
    matriufinal[1,x+4]=m2[:,x].std()
    matriufinal[2,x]=m3[:,x].mean()
    matriufinal[2,x+4]=m3[:,x].mean()
print(matriufinal)

[[5.18888889 3.57777778 1.42222222 0.26666667 0.34462361 0.30469576
  0.14740555 0.06666667]
 [6.2        2.8        4.25       1.35       0.5        0.2
  0.75       0.35      ]
 [6.64444444 2.96666667 5.6        1.96666667 6.64444444 2.96666667
  5.6        1.96666667]]


- Exercici 6
Calcula la quantitat de mostres per espècie.
Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [346]:
#La quantitat de mostres les hem obtingut de manera indirecta a l'exercici anterior:

print("La quantitat de mostres de l'espècie setosa és de:",index_setosa.size*4)
print("La quantitat de mostres de l'espècie versicolor és de:",index_versicolor.size*4)
print("La quantitat de mostres de l'espècie virginica és de:",index_virginica.size*4)

La quantitat de mostres de l'espècie setosa és de: 36
La quantitat de mostres de l'espècie versicolor és de: 8
La quantitat de mostres de l'espècie virginica és de: 36


In [347]:
dades.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [348]:
print('L´espècie amb la mitjana més gran de la variable sepal length és:',dades.target_names[np.argmax(matriufinal[:,0])])

L´espècie amb la mitjana més gran de la variable sepal length és: virginica


- Exercici 7
Calcula la matriu de correlació entre les variables.
Filtra els valors majors a la mitjana (de l'exercici 3) de la longitud dels pètals i mostra-ho. 
Troba la mostra amb els pètals més llargs.

In [384]:
#No tinc clar que s'hagi de fer d'aquesta manera:
matriucorr=np.empty((1,4))
for x in range(4):
    matriucorr[0,x] = np.corrcoef(matriunoespecies[:,x])
print(matriucorr)

[[1. 1. 1. 1.]]


In [375]:
filter_arr = []
for element in data[:,2]:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > mitjana_petal:
    filter_arr.append(element)


In [376]:
print("Les longituds de pètals superiors a la mitjana són:",filter_arr)

Les longituds de pètals superiors a la mitjana són: [4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 4.6, 3.9, 4.2, 4.0, 4.7, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 5.0, 4.5, 3.8, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4, 4.6, 4.0, 4.2, 4.2, 4.2, 4.3, 4.1, 6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5.0, 5.1, 5.3, 5.5, 6.7, 6.9, 5.0, 5.7, 4.9, 6.7, 4.9, 5.7, 6.0, 4.8, 4.9, 5.6, 5.8, 6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1, 5.9, 5.7, 5.2, 5.0, 5.2, 5.4, 5.1]


In [378]:
print("La longitud màxima de pètal  és de", np.amax(filter_arr),"cm.")

La longitud màxima de pètal  és de 6.9 cm.


## Part 2
Descripció:
Exercicis amb Dataframes.

- Exercici 1
Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.

Neteja el data set.

Airlines Delay: Airline on-time statistics and delay causes
Important

Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

In [385]:
#Aquesta part està basada amb el que hem fet a classe.
import pandas as pd

In [386]:
#Importem el csv
df=pd.read_csv('DelayedFlights.csv')

In [387]:
#Observem la capçalera i les primeres files del dataframe.
df

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4   2003.0        1955   
1                 1  2008      1           3          4    754.0         735   
2                 2  2008      1           3          4    628.0         620   
3                 4  2008      1           3          4   1829.0        1755   
4                 5  2008      1           3          4   1940.0        1915   
...             ...   ...    ...         ...        ...      ...         ...   
1936753     7009710  2008     12          13          6   1250.0        1220   
1936754     7009717  2008     12          13          6    657.0         600   
1936755     7009718  2008     12          13          6   1007.0         847   
1936756     7009726  2008     12          13          6   1251.0        1240   
1936757     7009727  2008     12          13          6   1110.0        1103   

         ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  \
0         2211.0        2225            WN        335  N712SW   
1         1002.0        1000            WN       3231  N772SW   
2          804.0         750            WN        448  N428WN   
3         1959.0        1925            WN       3920  N464WN   
4         2121.0        2110            WN        378  N726SW   
...          ...         ...           ...        ...     ...   
1936753   1617.0        1552            DL       1621  N938DL   
1936754    904.0         749            DL       1631  N3743H   
1936755   1149.0        1010            DL       1631  N909DA   
1936756   1446.0        1437            DL       1639  N646DL   
1936757   1413.0        1418            DL       1641  N908DL   

         ActualElapsedTime  CRSElapsedTime  AirTime  ArrDelay  DepDelay  \
0                    128.0           150.0    116.0     -14.0       8.0   
1                    128.0           145.0    113.0       2.0      19.0   
2                     96.0            90.0     76.0      14.0       8.0   
3                     90.0            90.0     77.0      34.0      34.0   
4                    101.0           115.0     87.0      11.0      25.0   
...                    ...             ...      ...       ...       ...   
1936753              147.0           152.0    120.0      25.0      30.0   
1936754              127.0           109.0     78.0      75.0      57.0   
1936755              162.0           143.0    122.0      99.0      80.0   
1936756              115.0           117.0     89.0       9.0      11.0   
1936757              123.0           135.0    104.0      -5.0       7.0   

        Origin Dest  Distance  TaxiIn  TaxiOut  Cancelled CancellationCode  \
0          IAD  TPA       810     4.0      8.0          0                N   
1          IAD  TPA       810     5.0     10.0          0                N   
2          IND  BWI       515     3.0     17.0          0                N   
3          IND  BWI       515     3.0     10.0          0                N   
4          IND  JAX       688     4.0     10.0          0                N   
...        ...  ...       ...     ...      ...        ...              ...   
1936753    MSP  ATL       906     9.0     18.0          0                N   
1936754    RIC  ATL       481    15.0     34.0          0                N   
1936755    ATL  IAH       689     8.0     32.0          0                N   
1936756    IAD  ATL       533    13.0     13.0          0                N   
1936757    SAT  ATL       874     8.0     11.0          0                N   

         Diverted  CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  \
0               0           NaN           NaN       NaN            NaN   
1               0           NaN           NaN       NaN            NaN   
2               0           NaN           NaN       NaN            NaN   
3               0           2.0           0.0       0.0            0.0   
4               0           NaN           NaN       NaN    

In [388]:
#Com tenim columnes que no podem visualitzar, ajustem les opcions per poder-ho fer.

pd.set_option('display.max_columns', None)

In [389]:
df.head()

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955   
1           1  2008      1           3          4    754.0         735   
2           2  2008      1           3          4    628.0         620   
3           4  2008      1           3          4   1829.0        1755   
4           5  2008      1           3          4   1940.0        1915   

   ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0   2211.0        2225            WN        335  N712SW              128.0   
1   1002.0        1000            WN       3231  N772SW              128.0   
2    804.0         750            WN        448  N428WN               96.0   
3   1959.0        1925            WN       3920  N464WN               90.0   
4   2121.0        2110            WN        378  N726SW              101.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   
4           115.0     87.0      11.0      25.0    IND  JAX       688     4.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                N         0           NaN           NaN   
1     10.0          0                N         0           NaN           NaN   
2     17.0          0                N         0           NaN           NaN   
3     10.0          0                N         0           2.0           0.0   
4     10.0          0                N         0           NaN           NaN   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       NaN            NaN                NaN  
1       NaN            NaN                NaN  
2       NaN            NaN                NaN  
3       0.0            0.0               32.0  
4       NaN            NaN                NaN

In [393]:
#Observem el total de dades, la seva tipologia per columna i el pes de l'arxiu.Una dada que considerem rellevant és el retard
#en l'arribada. Aquest el considerarem si és superior a 15 minuts. Veiem que hi ha diferents columnes relacionades amb 
#els retards.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype  
---  ------             -----  
 0   Unnamed: 0         int64  
 1   Year               int64  
 2   Month              int64  
 3   DayofMonth         int64  
 4   DayOfWeek          int64  
 5   DepTime            float64
 6   CRSDepTime         int64  
 7   ArrTime            float64
 8   CRSArrTime         int64  
 9   UniqueCarrier      object 
 10  FlightNum          int64  
 11  TailNum            object 
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object 
 18  Dest               object 
 19  Distance           int64  
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64  
 23  CancellationCode   object 
 24  Diverted           int64  
 25  CarrierDelay      

In [391]:
#Si el retard és inferior a 15 minuts, el posarem a zero.
#df_1=df['FlightNum','Arr_Delay','Diverted',]
df.ArrDelay[df['ArrDelay']<15]=0

C:\Users\77834175J\AppData\Local\Temp\ipykernel_22660\1669249672.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.ArrDelay[df['ArrDelay']<15]=0


In [392]:
df['ArrDelay']<15

0           True
1           True
2           True
3          False
4           True
           ...  
1936753    False
1936754    False
1936755    False
1936756     True
1936757     True
Name: ArrDelay, Length: 1936758, dtype: bool

In [6]:
#Analitzem els codis de cancel·lació.
df.CancellationCode.unique()

array(['N', 'A', 'B', 'C'], dtype=object)

In [ ]:
#Veiem que aquestes dades no ens aporten gaire informació rellevant 

In [396]:
#Comptabilizem els camps buits.
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [397]:
df.describe().T

count          mean           std     min        25%  \
Unnamed: 0         1936758.0  3.341651e+06  2.066065e+06     0.0  1517452.5   
Year               1936758.0  2.008000e+03  0.000000e+00  2008.0     2008.0   
Month              1936758.0  6.111106e+00  3.482546e+00     1.0        3.0   
DayofMonth         1936758.0  1.575347e+01  8.776272e+00     1.0        8.0   
DayOfWeek          1936758.0  3.984827e+00  1.995966e+00     1.0        2.0   
DepTime            1936758.0  1.518534e+03  4.504853e+02     1.0     1203.0   
CRSDepTime         1936758.0  1.467473e+03  4.247668e+02     0.0     1135.0   
ArrTime            1929648.0  1.610141e+03  5.481781e+02     1.0     1316.0   
CRSArrTime         1936758.0  1.634225e+03  4.646347e+02     0.0     1325.0   
FlightNum          1936758.0  2.184263e+03  1.944702e+03     1.0      610.0   
ActualElapsedTime  1928371.0  1.333059e+02  7.206007e+01    14.0       80.0   
CRSElapsedTime     1936560.0  1.343027e+02  7.134144e+01   -25.0       82.0   
AirTime            1928371.0  1.082771e+02  6.864261e+01     0.0       58.0   
ArrDelay           1928371.0  4.094390e+01  5.746982e+01     0.0        0.0   
DepDelay           1936758.0  4.318518e+01  5.340250e+01     6.0       12.0   
Distance           1936758.0  7.656862e+02  5.744797e+02    11.0      338.0   
TaxiIn             1929648.0  6.812975e+00  5.273595e+00     0.0        4.0   
TaxiOut            1936303.0  1.823220e+01  1.433853e+01     0.0       10.0   
Cancelled          1936758.0  3.268348e-04  1.807562e-02     0.0        0.0   
Diverted           1936758.0  4.003598e-03  6.314722e-02     0.0        0.0   
CarrierDelay       1247488.0  1.917940e+01  4.354621e+01     0.0        0.0   
WeatherDelay       1247488.0  3.703571e+00  2.149290e+01     0.0        0.0   
NASDelay           1247488.0  1.502164e+01  3.383305e+01     0.0        0.0   
SecurityDelay      1247488.0  9.013714e-02  2.022714e+00     0.0        0.0   
LateAircraftDelay  1247488.0  2.529647e+01  4.205486e+01     0.0        0.0   

                         50%         75%        max  
Unnamed: 0         3242558.0  4972466.75  7009727.0  
Year                  2008.0     2008.00     2008.0  
Month                    6.0        9.00       12.0  
DayofMonth              16.0       23.00       31.0  
DayOfWeek                4.0        6.00        7.0  
DepTime               1545.0     1900.00     2400.0  
CRSDepTime            1510.0     1815.00     2359.0  
ArrTime               1715.0     2030.00     2400.0  
CRSArrTime            1705.0     2014.00     2400.0  
FlightNum             1543.0     3422.00     9742.0  
ActualElapsedTime      116.0      165.00     1114.0  
CRSElapsedTime         116.0      165.00      660.0  
AirTime                 90.0      137.00     1091.0  
ArrDelay                24.0       56.00     2461.0  
DepDelay                24.0       53.00     2467.0  
Distance               606.0      998.00     4962.0  
TaxiIn                   6.0        8.00      240.0  
TaxiOut                 14.0       21.00      422.0  
Cancelled                0.0        0.00        1.0  
Diverted                 0.0        0.00        1.0  
CarrierDelay             2.0       21.00     2436.0  
WeatherDelay             0.0        0.00     1352.0  
NASDelay                 2.0       15.00     1357.0  
SecurityDelay            0.0        0.00      392.0  
LateAircraftDelay        8.0       33.00     1316.0

In [398]:
df[df['ArrDelay']<15].shape[0]

680883

In [399]:
df.Cancelled.value_counts()

0    1936125
1        633
Name: Cancelled, dtype: int64

In [400]:
df.Diverted.value_counts()

0    1929004
1       7754
Name: Diverted, dtype: int64

In [401]:
df.Diverted.value_counts()[1] + df.Cancelled.value_counts()[1]

8387

In [402]:
df['ArrDelay'].isnull().sum()

8387

In [403]:
df.ArrDelay[df['ArrDelay']<15] = 0

C:\Users\77834175J\AppData\Local\Temp\ipykernel_22660\831260710.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.ArrDelay[df['ArrDelay']<15] = 0


In [404]:
df[df['ArrDelay']<15]

Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0                 0  2008      1           3          4   2003.0        1955   
1                 1  2008      1           3          4    754.0         735   
2                 2  2008      1           3          4    628.0         620   
4                 5  2008      1           3          4   1940.0        1915   
6                10  2008      1           3          4    706.0         700   
...             ...   ...    ...         ...        ...      ...         ...   
1936739     7009646  2008     12          13          6   1100.0        1045   
1936740     7009652  2008     12          13          6   1200.0        1150   
1936750     7009702  2008     12          13          6   1531.0        1522   
1936756     7009726  2008     12          13          6   1251.0        1240   
1936757     7009727  2008     12          13          6   1110.0        1103   

         ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  \
0         2211.0        2225            WN        335  N712SW   
1         1002.0        1000            WN       3231  N772SW   
2          804.0         750            WN        448  N428WN   
4         2121.0        2110            WN        378  N726SW   
6          916.0         915            WN        100  N690SW   
...          ...         ...           ...        ...     ...   
1936739   1350.0        1347            DL       1530  N920DL   
1936740   1924.0        1921            DL       1538  N6710E   
1936750   1822.0        1823            DL       1612  N916DN   
1936756   1446.0        1437            DL       1639  N646DL   
1936757   1413.0        1418            DL       1641  N908DL   

         ActualElapsedTime  CRSElapsedTime  AirTime  ArrDelay  DepDelay  \
0                    128.0           150.0    116.0       0.0       8.0   
1                    128.0           145.0    113.0       0.0      19.0   
2                     96.0            90.0     76.0       0.0       8.0   
4                    101.0           115.0     87.0       0.0      25.0   
6                    130.0           135.0    106.0       0.0       6.0   
...                    ...             ...      ...       ...       ...   
1936739              110.0           122.0     91.0       0.0      15.0   
1936740              264.0           271.0    238.0       0.0      10.0   
1936750              111.0           121.0     88.0       0.0       9.0   
1936756              115.0           117.0     89.0       0.0      11.0   
1936757              123.0           135.0    104.0       0.0       7.0   

        Origin Dest  Distance  TaxiIn  TaxiOut  Cancelled CancellationCode  \
0          IAD  TPA       810     4.0      8.0          0                N   
1          IAD  TPA       810     5.0     10.0          0                N   
2          IND  BWI       515     3.0     17.0          0                N   
4          IND  JAX       688     4.0     10.0          0                N   
6          IND  MCO       828     5.0     19.0          0                N   
...        ...  ...       ...     ...      ...        ...              ...   
1936739    MCI  ATL       692     7.0     12.0          0                N   
1936740    PDX  ATL      2172    11.0     15.0          0                N   
1936750    MCI  ATL       692     9.0     14.0          0                N   
1936756    IAD  ATL       533    13.0     13.0          0                N   
1936757    SAT  ATL       874     8.0     11.0          0                N   

         Diverted  CarrierDelay  WeatherDelay  NASDelay  SecurityDelay  \
0               0           NaN           NaN       NaN            NaN   
1               0           NaN           NaN       NaN            NaN   
2               0           NaN           NaN       NaN            NaN   
4               0           NaN           NaN       NaN            NaN   
6               0           NaN           NaN       NaN    

In [405]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [406]:
df = df[(df.Cancelled == 0) & (df.Diverted == 0)]

In [407]:
df.isnull().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                   0
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   3
ActualElapsedTime         0
CRSElapsedTime            0
AirTime                   0
ArrDelay                  0
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                    0
TaxiOut                   0
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         680883
WeatherDelay         680883
NASDelay             680883
SecurityDelay        680883
LateAircraftDelay    680883
dtype: int64

In [408]:
df.duplicated().sum()

0

In [409]:
df_limpio = df[['FlightNum', 'AirTime', 'ArrDelay', 'UniqueCarrier']]
df_limpio.head()

FlightNum  AirTime  ArrDelay UniqueCarrier
0        335    116.0       0.0            WN
1       3231    113.0       0.0            WN
2        448     76.0       0.0            WN
3       3920     77.0      34.0            WN
4        378     87.0       0.0            WN

In [410]:
df_sample = df_limpio.sample(n=200000, random_state=12)

In [411]:
df_sample.head()

FlightNum  AirTime  ArrDelay UniqueCarrier
1535131       2208     41.0       0.0            WN
221646        2292     91.0      17.0            XE
1849672       5630     52.0      78.0            EV
1354141       4524    117.0     134.0            EV
1935802        723    142.0      62.0            DL

- Exercici 2
Fes un informe complet del dataset:

Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.
Mostra quina és les aerolínies amb més endarreriments acumulats.
Quins són els vols més llargs?

In [412]:
#Mostrem les 10 companyies amb la mitjana de retards més gran. 
df_sample.groupby('UniqueCarrier')['ArrDelay'].mean().sort_values(ascending=False).head(10)

UniqueCarrier
B6    54.465780
YV    53.368527
OH    50.989251
XE    48.544366
UA    47.199261
9E    46.961753
AA    45.972467
EV    45.780170
MQ    44.263850
OO    43.521909
Name: ArrDelay, dtype: float64

In [413]:
#Aquí obtenim la suma de minuts de retard per cada companyia
df_sample.groupby('UniqueCarrier')['ArrDelay'].sum().sort_values(ascending=False).head(10)

UniqueCarrier
WN    1104206.0
AA     908324.0
UA     689534.0
MQ     643198.0
OO     602909.0
XE     514813.0
DL     448245.0
CO     419793.0
EV     393389.0
YV     372032.0
Name: ArrDelay, dtype: float64

In [414]:
#Aquí comptem el nombre de retards.
df_sample.groupby('UniqueCarrier')['ArrDelay'].count().sort_values(ascending=False).head(10)

UniqueCarrier
WN    39079
AA    19758
UA    14609
MQ    14531
OO    13853
DL    11799
XE    10605
CO    10335
US    10164
EV     8593
Name: ArrDelay, dtype: int64

Aquests càlculs ens permeten estudiar el concepte de retard amb diferents punts de vista. En funció del tipus d'encàrrec, es poden utilizar uns o altres resultats. El problema d'aquests càlculs és que tenen en compte retards inferiors a 15 minuts, els quals no els hem considerat retard, i seria convenient que quedessin fora de l'estudi.

In [415]:
#Creem la columna Delayed, indicant si aquest retard és cert o fals, en funció de si és menor a 15 minuts o no.
df_sample['Delayed'] = df_sample['ArrDelay'] >= 15

In [416]:
df_sample.head()

FlightNum  AirTime  ArrDelay UniqueCarrier  Delayed
1535131       2208     41.0       0.0            WN    False
221646        2292     91.0      17.0            XE     True
1849672       5630     52.0      78.0            EV     True
1354141       4524    117.0     134.0            EV     True
1935802        723    142.0      62.0            DL     True

In [419]:
df_sample.groupby('UniqueCarrier')['Delayed'].mean().sort_values(ascending=False).head(10)

UniqueCarrier
OH    0.764096
YV    0.760866
NW    0.700945
9E    0.699220
AA    0.696326
XE    0.692975
EV    0.691609
B6    0.691489
MQ    0.687565
UA    0.678349
Name: Delayed, dtype: float64

In [420]:
df_sample.groupby('UniqueCarrier')['Delayed'].sum().sort_values(ascending=False).head(10)

UniqueCarrier
WN    21096
AA    13758
MQ     9991
UA     9910
OO     9327
DL     7481
XE     7349
US     6269
CO     6154
EV     5943
Name: Delayed, dtype: int64

- Exercici 3
Exporta el dataset net i amb les noves columnes a Excel.

In [421]:
df_sample.to_excel('DataFrame_Modul3.xlsx', sheet_name='DataFrame_Modul3')